services:
  - type: web
    name: howarts_rails
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake assets:precompile && bundle exec rake db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        value: "tu_rails_master_key"
      - key: DATABASE_URL
        value: "postgresql://<DB_USERNAME>:<DB_PASSWORD>@<DB_HOST>:<DB_PORT>/<DB_NAME>"
      - key: RAILS_ENV
        value: "production"
