services:
  - type: web
    name: howarts_rails
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false # Configura esta variable en el panel de Render en lugar de incluirla en este archivo
      - key: DATABASE_URL
        value: postgresql://USERNAME:PASSWORD@HOST:PORT/DATABASE_NAME # Reemplaza con la URL correcta de tu base de datos en Render
