services:
  - type: web
    name: howarts_rails
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        value: 460e063ce814b42e0fc0b9f1fa7d5724 # Reemplaza esto con tu RAILS_MASTER_KEY real
      - key: DATABASE_URL
        value: "postgresql://postgres:patoprogramador@localhost:5432/howarts_rails_production" # Configura tu conexión PostgreSQL correctamente
